### ISSUE TITLE
Invalid link to documentation in Readme

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [davebulaval/notification#3]
Link to documentation in readme file [https://notificationdoc.ca](https://notificationdoc.ca) does not work.
It should be corrected as [https://notificationdoc.ca/index.html](https://notificationdoc.ca/index.html)

**Comment by davebulaval** [comment]
@harshajayaweeraXHJ Did you close it because it's a mistake or is really not working ?
Tks for the help.
